// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import checkAvailable from './src/utils/checkAvailable';

export default defineConfig({
  schema: './src/database/prisma/schema.prisma',
  migrations: {
    path: './src/database/prisma/migrations',
    seed: 'node dist/src/database/prisma/seed.js',
  },
  datasource: {
    url: checkAvailable(process.env['DATABASE_URL'], 'DATABASE_URL'),
  },
});
